# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute correlation matrix
#' @param corfun_name_string Choice of kernel function
#' @param xSqrd_mat Matrix of squared difference between inputs x's
#' @param tau Inverse lengthscale parameter
#' @return cormat Correlation matrix from vector of inputs x's
#' @details The correlation matrix with corresponding choice of kernel: For RBF kernel \deqn{C(x_i,x_j) = \exp(-\tau^2/2 \times d^2),}
#' for Matern 1/2 kernel \deqn{C(x_i,x_j) = \exp(-\tau \times d),}
#' for Matern 3/2 kernel \deqn{C(x_i,x_j) = (1 + \sqrt{3} \times\tau \times d)\exp(-\sqrt{3}\times\tau \times d),}
#' and for Matern 5/2 kernel \deqn{C(x_i,x_j) = (1 + \sqrt{3} \times\tau \times d + \sqrt{5}/\sqrt{3} \times\tau^2 \times d^2)\exp(-\sqrt{5}\times\tau \times d),}
#' with \eqn{d = || x_i - x_j ||_2^2} is the squared distance between locations i and j.
#' @noRd
NULL

#' @title Kronecker matrix-vector product (Steeb & Hardy, 2011)
#' @description \deqn{(A \otimes B)v = \text{vectorise}(BVA^\top)}
#' @param A Left matrix
#' @param B Right matrix
#' @param v vector
#' @return Kronecker matrix-vector product
#' @noRd
NULL

#' @title Fit intra-regional model using L-BFGS
#' @param theta_init unrestricted initialization of parameters for 1 region
#' @param X_region Vectorized (LM) - data matrix of signals of 1 region
#' @param voxel_coords L x 3 matrix of voxel coordinates
#' @param time_sqrd_mat M x M temporal squared distance matrix
#' @param kernel_type_id Choice of spatial kernel
#' @param setting Choice of covariance structure
#' @noRd
opt_intra <- function(theta_init, X_region, voxel_coords, time_sqrd_mat, kernel_type_id, cov_setting_id, verbose) {
    .Call('_qfuncMM_opt_intra', PACKAGE = 'qfuncMM', theta_init, X_region, voxel_coords, time_sqrd_mat, kernel_type_id, cov_setting_id, verbose)
}

eval_stage1_nll <- function(theta, X_region, voxel_coords, time_sqrd_mat, kernel_type_id) {
    .Call('_qfuncMM_eval_stage1_nll', PACKAGE = 'qfuncMM', theta, X_region, voxel_coords, time_sqrd_mat, kernel_type_id)
}

#' @title Fit inter-regional model using L-BFGS
#' @param theta_init unrestricted initialization of parameters for
#'  inter-regional model
#' @param dataRegion1 Vectorized region 1 data matrix
#' @param dataRegion2 Vectorized region 2 data matrix
#' @param voxel_coords_1 Region 1 voxel coordinates
#' @param voxel_coords_2 Region 2 voxel coordinates
#' @param time_sqrd_mat M x M temporal squared distance matrix
#' @param stage1ParamsRegion1 Regional parameters from stage 1
#' @param stage1ParamsRegion2 Regional parameters from stage 1
#' @param kernel_type_id Choice of spatial kernel
#' @return List of 3 components:
#'   theta: Estimated inter-regional parameters
#'   sigma2_ep: Estimated noise variance
#'   objective: optimal loss (negiatve log-likelihood) found.
#' @noRd
opt_inter <- function(theta_init, data_r1, data_r2, coords_r1, coords_r2, time_sqrd_mat, stage1_r1, stage1_r2, cov_setting_id1, cov_setting_id2, kernel_type_id, verbose) {
    .Call('_qfuncMM_opt_inter', PACKAGE = 'qfuncMM', theta_init, data_r1, data_r2, coords_r1, coords_r2, time_sqrd_mat, stage1_r1, stage1_r2, cov_setting_id1, cov_setting_id2, kernel_type_id, verbose)
}

