# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute correlation matrix
#' @param corfun_name_string Choice of kernel function
#' @param xSqrd_mat Matrix of squared difference between inputs x's
#' @param tau Inverse lengthscale parameter
#' @return cormat Correlation matrix from vector of inputs x's
#' @details The correlation matrix with corresponding choice of kernel: For RBF kernel \deqn{C(x_i,x_j) = \exp(-\tau^2/2 \times d^2),}
#' for Matern 1/2 kernel \deqn{C(x_i,x_j) = \exp(-\tau \times d),}
#' for Matern 3/2 kernel \deqn{C(x_i,x_j) = (1 + \sqrt{3} \times\tau \times d)\exp(-\sqrt{3}\times\tau \times d),}
#' and for Matern 5/2 kernel \deqn{C(x_i,x_j) = (1 + \sqrt{3} \times\tau \times d + \sqrt{5}/\sqrt{3} \times\tau^2 \times d^2)\exp(-\sqrt{5}\times\tau \times d),}
#' with \eqn{d = || x_i - x_j ||_2^2} is the squared distance between locations i and j.
#' @noRd
NULL

#' @title Kronecker matrix-vector product (Steeb & Hardy, 2011)
#' @description \deqn{(A \otimes B)v = \text{vectorise}(BVA^\top)}
#' @param A Left matrix
#' @param B Right matrix
#' @param v vector
#' @return Kronecker matrix-vector product
#' @references Willi-Hans Steeb and Yorick Hardy. Matrix calculus and Kronecker product: a practical approach to linear and multilinear algebra. World Scientific Publishing Company, 2011.
#' @noRd
NULL

#' Get distance squared matrix for a region
#' @param coords Matrix of coordinates of voxels. Each row is a voxel.
#' @return Matrix of squared distances between voxels
#' @noRd
get_dist_sqrd_mat <- function(coords) {
    .Call('_qfuncMM_get_dist_sqrd_mat', PACKAGE = 'qfuncMM', coords)
}

#' @title Fit intra-regional model using L-BFGS
#' @param theta_init unrestricted initialization of parameters for 1 region
#' @param X_region Data matrix of signals of 1 region
#' @param Z_region fixed-effects design matrix of 1 region
#' @param dist_sqrd_mat Spatial squared distance matrix
#' @param time_sqrd_mat Temporal squared distance matrix
#' @param L Number of voxels
#' @param M Number of time points
#' @param kernel_type_id Choice of spatial kernel
#' @return List of 2 components:
#' \item{theta}{estimated intra-regional parameters}
#' \item{nu}{fixed-effect estimate}
#' @noRd
opt_intra <- function(theta_init, X_region, Z_region, dist_sqrd_mat, time_sqrd_mat, L, M, kernel_type_id) {
    .Call('_qfuncMM_opt_intra', PACKAGE = 'qfuncMM', theta_init, X_region, Z_region, dist_sqrd_mat, time_sqrd_mat, L, M, kernel_type_id)
}

#' @title Fit inter-regional model using L-BFGS
#' @param theta_init unrestricted initialization of parameters  for inter-regional model
#' @param X Data matrix of signals of 2 regions
#' @param Z fixed-effects design matrix of 2 regions
#' @param dist_sqrdMat_1 Block component for that region 1
#' @param dist_sqrdMat_2 Block component for that region 2
#' @param kernel_type_id Choice of spatial kernel
#' @param stage1_regional Regional parameters from stage 1
#' @return List of 3 components:
#' \item{theta}{estimated inter-regional parameters}
#' \item{asymptotic_var}{asymptotic variance of transformed correlation coefficient}
#' \item{rho_transformed}{Fisher transformation of correlation coefficient}
#' @noRd
opt_inter <- function(theta_init, X, Z, dist_sqrdMat_1, dist_sqrdMat_2, time_sqrd_mat, stage1_regional, kernel_type_id) {
    .Call('_qfuncMM_opt_inter', PACKAGE = 'qfuncMM', theta_init, X, Z, dist_sqrdMat_1, dist_sqrdMat_2, time_sqrd_mat, stage1_regional, kernel_type_id)
}

